name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "X The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Y This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Z The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "P The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Q The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "R This job's status is ${{ job.status }}."
